### ISSUE TITLE
是否可以执行bat命令或者运行命令

### ISSUE THREAD

**Issue by Jace-y** [hui-Zz/RunAny#10]
添加到菜单以后不显示
-系统(&Sys)
	cmd.exe
	控制面板(&S)|Control.exe
	flushdns(&A)|E:\Mycode\script\flushdns.BAT

添加到文件也不显示
另外求教如何能快捷键打开设备管理器

**Comment by hui-Zz** [comment]
@Jace-y  已经更新了，你可以到文件中复制设备管理器的命令：[实用命令.ini](https://github.com/hui-Zz/RunAny/blob/master/%E5%AE%9E%E7%94%A8%E9%85%8D%E7%BD%AE/%E5%AE%9E%E7%94%A8%E5%91%BD%E4%BB%A4.ini)
关于你说的“不显示”一般情况是没问题的，不知道你具体是怎样，麻烦加一下群帮你解决：246308937
