### ISSUE TITLE
directory opus 里无法快捷打开文件

### ISSUE THREAD

**Issue by jamesfu1978** [hui-Zz/RunAny#111]
在 directory opus 选中文件后按 ~ 只弹出常规的菜单，不能弹出设置的快捷打开方式。
比如我设置txt文件用 notepad++和记事本打开，但在 directory opus 里选中txt文件按`只弹出常规的菜单。（在文件资源管理器里进行同样的操作正常弹出 notepad++和记事本）
并且在directory opus 选中文件后按 ~ 会将该文件复制到剪切板中（在文件资源管理器里也是一样会复制文件）
比如我选中0001.txt后按 ~ 就会复制该文本文档

**Comment by hui-Zz** [comment]
打开RunAny设置，找到高级设置，找到 `[选中] 自定义在一些软件界面获取选中内容的热键`
在后面添加 `,dopus.exe` （注意中间要用英文逗号分隔）
点击确定后试一下

如果还是不行，再次打开高级设置，找到 `[选中] 指定软件获取选中目标到剪贴板等待时间，全局其他软件默认0.1秒`
添加 `dopus.exe`
还有在下面的 `[选中] 指定软件获取选中目标到剪贴板等待时间，全局其他软件默认0.1秒`
填写 `1.2` ~ `2`  秒之间

**Comment by jamesfu1978** [comment]
![image](https://github.com/hui-Zz/RunAny/assets/46924239/035a11ab-920b-4f77-9a7e-2a8399beaabb)
谢谢，按照上面的方法改了这些设置后，可以正常使用，不知道还会不会有bug，后续有问题再反馈~
