### ISSUE TITLE
能不能不启用Everything?

### ISSUE THREAD

**Issue by zsedcbm** [hui-Zz/RunAny#12]
我把文件里面的所有路径都设置成绝对路径了,能不能不启用Everything?

**Comment by hui-Zz** [comment]
@zsedcbm  如果只是不想让Everything一直在后台常驻，可以打开RunAny设置-Everything设置：勾选“Everything自动关闭”，确定后就生效了。 （如果还不满意就修改RunAny.ahk，删除“初始化everything安装路径”那段代码，不会的话可以加QQ群246308937，帮你生成一个无Everything的RunAny.exe）
