### ISSUE TITLE
启用停用RunAny快捷键能否使用同一个?

### ISSUE THREAD

**Issue by zsedcbm** [hui-Zz/RunAny#13]
目前只有停用RunAny,不能再按此快捷键进行启用操作.

如果可以的话,停用快捷键能够支持区分是左ctrl还是右ctrl, 作为开发人员,平时用的快捷键太多了,经常会重复的.

**Comment by hui-Zz** [comment]
@zsedcbm  停用启用是一个功能的，但是停用后会禁用RunAny所有快捷键，所以当然启用快捷键也被禁了😂，需要右点击图标按s键，或者再点击停用就恢复了。

左右Ctrl是支持的，打开RunAny设置界面，右下角点击RunAnyConfig.ini（或右击图标Ctrl+D打开）
找到RunASuspendKey（没有的需要先随便配置一个热键），然后把^F1（Ctrl+F1）改成 ` <^F1 `或 ` >^F1 ` 就是左或右Ctrl（<代表左，>代表右），想了解更多可以看：[AHK热键文档](https://wyagd001.github.io/zh-cn/docs/Hotkeys.htm)
