### ISSUE TITLE
Windows Defender报毒

### ISSUE THREAD

**Issue by wdssmq** [hui-Zz/RunAny#16]
![Windows Defender报毒](https://user-images.githubusercontent.com/8186642/43296129-01f0a822-917c-11e8-99ec-fcbb48ea0e80.png)

**Comment by hui-Zz** [comment]
@wdssmq 在一些电脑的Windows Defender 版本上我也遇到了误报RunAny病毒的情况，目前有两种解决方法：
1、如果你介意误报，可以把RunAny.exe删除，然后把RunPlugins目录下的AHK.exe（或你安装的AutoHotkey.exe）复制一份改名为RunAny.exe替换掉原来的，这样之后会自动调用RunAny.ahk来启动，功能是一致的。

2、在Windows Defender的白名单添加RunAny为排除项，这样就不会提示误报，操作可参考百度经验：https://jingyan.baidu.com/article/0964eca2473e9b8285f5363d.html
