### ISSUE TITLE
能否增加javascript,vbscript功能

### ISSUE THREAD

**Issue by lbgws2** [hui-Zz/RunAny#17]
在少数派看到介绍的文章,试用下,感赏非常好!!正是我苦苦追寻的工具
之前也试用过相关快速启动工具,但都不太理想.
RunAny满足了我绝大部分的需求,衷心感谢您的辛苦付出.
PS:提一个小建议,能否为RunAny增加脚本功能,可以运行自定义javascript,vbscript,脚本,有了脚本的加持,RunAny的用武之地会更加强大

另介绍另外一个软件,capslock+   https://cjkis.me/capslock+/#clTabScript
作者就是使用AHK编写,实现了内置脚本功能.但是capslock+使用不方便的地方在于要配合capslock键使用,功能多了使用不方便,手指不够灵活

**Comment by hui-Zz** [comment]
@lbgws2 一键公式计算已经用JS脚本eval实现了，另外RunAny还新增了大量插件功能，欢迎多多提出建议
