### ISSUE TITLE
希望支持「变量文件夹路径」

### ISSUE THREAD

**Issue by rockbenben** [hui-Zz/RunAny#18]
Runany在家里和公司电脑都安装了，但由于电脑用户名不同，导致要额外进行设置。

能不能增加变量文件夹路径支持？
例如：
C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by hui-Zz** [comment]
@rockbenben 是支持的。
一、AHK环境变量：
`A_UserName` 是 用户名
`%A_WinDir%` 是 `C:\Windows`
更多可见 https://wyagd001.github.io/zh-cn/docs/Variables.htm#OSVersion 最底部的[操作系统和用户信息]

二、系统环境变量：
` IE|%ProgramFiles%\Internet Explorer\iexplore.exe ` 是`C:\Program Files\internet explorer\iexplore.exe`
目前还没完全支持Windows默认环境变量，下个版本会全部支持

**Comment by rockbenben** [comment]
解决了，多谢
用AHK变量就可以处理，%A_Startup%
