### ISSUE TITLE
不能支持菜单嵌套吗?

### ISSUE THREAD

**Issue by Eviwang** [hui-Zz/RunAny#22]

**Comment by hui-Zz** [comment]
支持的。
以 -开头为1级菜单， --名称为2级菜单，以此类推
如：-app应用 是1级菜单、--img图像处理 是2级菜单
还有 可以在修改菜单树界面，勾选整个菜单再点移动到...另一个菜单下，就会自动变为2级菜单

**Comment by Eviwang** [comment]
好像最多只能两级？然后不能添加新的一级菜单。只能用默认的？

**Comment by hui-Zz** [comment]
普通用户是两级就够用了，更高级的用法你可以使用托盘功能“修改菜单”下面的“修改文件”手动修改菜单文件RunAny.ini
-是1级，--是2级，---是3级……到增加N级菜单
