### ISSUE TITLE
每次开机启动都会出现everything启动异常窗口

### ISSUE THREAD

**Issue by tuchit** [hui-Zz/RunAny#23]
![111](https://user-images.githubusercontent.com/30788338/67137573-3c156100-f26a-11e9-9d44-9da2fb672c5c.png)
如图，每次启动电脑都会出现，不论按不按everything的UAC确定窗口都如此
已经通过**process explorer**查明是RA的锅。

虽然不影响任何使用，但是每次要点下确定很烦

**Comment by hui-Zz** [comment]
@tuchit  
RunAny需要Everything正常运行并能搜索文件，所以请按照窗口提示里写的，在任务栏右下角托盘找到Everthing图标（橙色的放大镜）双击鼠标左键，打开后再点顶部的“工具“，再点“选项”打开设置界面，最后定位设置左边的常规里面，找到“Everything服务”并打上勾，这样安装好Everything服务后就不用每次弹窗了，而且不仅占用非常小还能大大加快搜索文件速度！

**Comment by tuchit** [comment]
OK，好了谢谢
