### ISSUE TITLE
批量搜索 - RunAny文档

### ISSUE THREAD

**Issue by hui-Zz** [hui-Zz/RunAny#38]
https://hui-zz.github.io/RunAny/#/batch-search 

 Description

**Comment by UnderCooled** [comment]
翻译应为：`翻译(&F)|https://translate.google.cn/#auto|zh-CN|%s`
没有 `%s` 会导致这个项目出现在一般列表里头

**Comment by hui-Zz** [comment]
@UnderCooled 这个可以随自己喜欢决定是否添加，有的时候也会不选中文字打开网站后再输入翻译
