### ISSUE TITLE
遇到一个问题

### ISSUE THREAD

**Issue by linux7594** [hui-Zz/RunAny#51]
在windows 10 的情况下，无法创建多级目录打开软件（windows 7下可以正常使用）

这是出现的状况：
![image](https://user-images.githubusercontent.com/59188424/71392789-60afff80-2644-11ea-9d59-02193f73d2cf.png)

这是runany.ini 配置文件：
![image](https://user-images.githubusercontent.com/59188424/71392840-a076e700-2644-11ea-919b-390f50162a15.png)

同样的配置在windows 7 下可以正常使用：
![image](https://user-images.githubusercontent.com/59188424/71392874-c3090000-2644-11ea-9fa0-1ea8a531f0a3.png)

**Comment by hui-Zz** [comment]
因为你windows 10 电脑上没有安装过Chrome.exe 自然就是没有的，你如果要始终显示就在RunAny设置里面 - RunAny应用菜单 - 取消 隐藏失效项

**Comment by linux7594** [comment]
我已经安装了chrome ，但是依然无效，不但chrome 无效，即使我额外指定其他的exe 依然无效

![image](https://user-images.githubusercontent.com/59188424/71401713-9e715000-2665-11ea-980c-801a2ab5c432.png)

![image](https://user-images.githubusercontent.com/59188424/71401737-af21c600-2665-11ea-907c-4bd93ecd4d13.png)

**Comment by linux7594** [comment]
> 因为你windows 10 电脑上没有安装过Chrome.exe 自然就是没有的，你如果要始终显示就在RunAny设置里面 - RunAny应用菜单 - 取消 隐藏失效项

切换成绝对路径就可以，已解决问题
