### ISSUE TITLE
无法以管理员启动

### ISSUE THREAD

**Issue by linux7594** [hui-Zz/RunAny#52]
我尝试用ctrl+shift+快捷键c，来以管理员模式快速打开cmd, 但是它没有反应
我又试着给它加上快捷键& C 但是依然没有反应，
但是sys下的控制面板可以正常启动

这是初始化后的情况：
![image](https://user-images.githubusercontent.com/59188424/71392986-488cb000-2645-11ea-84fc-8ee3f9fc2963.png)

这是绑定快捷键之后的情况

![image](https://user-images.githubusercontent.com/59188424/71393043-84c01080-2645-11ea-935e-3f28b9044924.png)

**Comment by hui-Zz** [comment]
@linux7594 目前尚不清楚为什么Ctrl+Shift+C无效，而换成其他字母可以，可能为系统热键保留等原因

**Comment by linux7594** [comment]
确实是快捷键原因，切换成M就行了
