### ISSUE TITLE
想请问下

### ISSUE THREAD

**Issue by linux7594** [hui-Zz/RunAny#53]
这是款很棒的软件！
但是我遇到一个奇怪的地方，二级目录似乎会将它下面的所有东西合并，即使是不属于它的
但是我不想让他们合并在一起，有什么方法可以解决吗？

这是出现的状况：
![image](https://user-images.githubusercontent.com/59188424/71393191-6ad2fd80-2646-11ea-97ac-6f5200763615.png)

这是配置文件：
![image](https://user-images.githubusercontent.com/59188424/71393259-cd2bfe00-2646-11ea-91e7-ca439eb76600.png)

**Comment by hui-Zz** [comment]
你把RunAny.ini内容拉在最下面有示例：
-
;1级分隔符【-】并且使下面项目都回归1级分类
QQ.exe
想让QQ.exe不归于上面的二级目录，就是在上面加单独一行分隔符 -

**Comment by linux7594** [comment]
好的，已经改正我自己的错误，确实是很方便的软件，谢谢
