### ISSUE TITLE
win7和win10下的一点问题

### ISSUE THREAD

**Issue by arliong** [hui-Zz/RunAny#54]
很好用的软件,和everything结合的思路很巧妙, 可以在多台PC延续使用习惯.

我遇到一些问题, 烦请帮忙, 谢谢!

1, win7环境, 我设置热键如下, 不起作用. 反倒是在记事本编辑时发现,在输入 '#qq'时会启动qq.
推测是无法把#识别成win键.

QQ:*X:#QQ|QQ.exe
微信:*X:#WX|D:\Program Files (x86)\Tencent\WeChat\WeChat.exe

2, win7环境的系统截图snippingtools.exe设置了没有反应

	截图工具(&A)|%A_WinDir%\system32\SnippingTool.exe
	Snipaste(&S)|Snipaste.exe

3, win10环境, 对于win10 软件仓库安装的app, 不知道怎么启动.
比如 Edge, 截图和草图, 便笺, 网易云音乐等等

**Comment by hui-Zz** [comment]
@arliong  不好意思回复慢了，其实可以加QQ群246308937这样我会更快的回复。

1。 热字符串和全局热键是两个独立并存的方式，你可以对一个菜单项同时设置全局热键和热字符串，`#qq`的触发条件是按Shift再按3再按两下qq，而全局热键只能设置为`#q` 就是<kbd>Win</kbd>+<kbd>Q</kbd>键，没有Win+qq的操作

2。SnippingTool.exe是Win10系统自带的截图工具，Win7是没有的，你可以在Win7电脑的everything中搜索SnippingTool，搜索没有的话RunAny当然也就找不到

3。对于Win10的uwp应用，我目前没有比较好的启动方式，不过可以利用生成快捷方式，再在RunAny中启动快捷方式来启动。
按Win+R运行：explorer.exe shell:::{4234d49b-0245-4df3-b780-3893943456e1}
打开Applications窗口后，找到想要的应用，右键“创建快捷方式”，然后在RunAny菜单中添加同名快捷方式.lnk就可以快捷运行了

**Comment by arliong** [comment]
谢谢你的解惑, 我今天才知道 热字符串 # qq 是按shift,3, qq, 请问相关的资料哪里可以看到? 

另外, win7附件的截图工具我发送快捷方式到桌面, 然后查看属性获得该目标是:%windir%\system32\SnippingTool.exe
然而我用了三个写法都不能让截图工具在runany的菜单中出现
ini中三种写法:
	截图工具(&A)|%A_WinDir%\system32\SnippingTool.exe
	截图工具1|%windir%\system32\SnippingTool.exe
	截图工具2|截图工具.lnk
