### ISSUE TITLE
快捷方式获取有点问题

### ISSUE THREAD

**Issue by freesoft0000** [hui-Zz/RunAny#55]
打开软件后，生成了桌面的快捷方式菜单。
hms81.exe (2).lnk这个只显示了hms81

**Comment by hui-Zz** [comment]
@freesoft0000 
因为RunAny支持exe空格后传递参数啊，所以你这样的文件名就会被识别为
程序名：hms81.exe
参数：(2).lnk
不能这样命名，建议改成：hms81.lnk
