### ISSUE TITLE
求教快速复制文件到指定文件夹的脚本

### ISSUE THREAD

**Issue by rodygdut** [hui-Zz/RunAny#57]
比如在文件管理器中，选定 一个文件 ，按快捷键alt+c，自动将此文件复制到 指定文件夹 E:\temp归档，

使用 按`+字母 的快捷方式也可以，请大神指教，谢谢！

**Comment by hui-Zz** [comment]
```ini
复制选中文件到D盘|cmd.exe /c "xcopy /h /y "%getZz%" "D:\""
```
在RunAny.ini里面使用这个就可以实现把选中文件复制到D盘（可自定义其他文件夹）

**Comment by rodygdut** [comment]
谢谢，真的太方便了，以后归档文件就快多了

**Comment by rodygdut** [comment]
你给的引号可能有问题，测试不行，下面这个可以了
复制选中文件到D盘|cmd.exe /c "xcopy /h /y "%getZz%" D:\\"

**Comment by rodygdut** [comment]
还有个问题，在复制完文件后，怎么把选中文件的文件名赋值给%Clipboard%，下次直接Ctrl+v粘贴出文件名

**Comment by hui-Zz** [comment]
这是第二个功能，复制文件名可以看插件huiZz_System里的【复制路径】：https://hui-zz.gitee.io/runany/#/plugins-help?id=huizz_system%e7%b3%bb%e7%bb%9f%e6%93%8d%e4%bd%9c%e6%8f%92%e4%bb%b6%e4%bd%bf%e7%94%a8%e6%96%b9%e6%b3%95
