### ISSUE TITLE
配置文件中无法使用参数

### ISSUE THREAD

**Issue by MisterZakary** [hui-Zz/RunAny#58]
版本:5.7.1
按照文档说明，如果程序需要使用参数 ，可以使用【程序名 空格 参数】的方式，但是经过实际测试这样会找不到应用程序，测试用例【everything.exe -s】。而且和 C:\Program Files 这样的路径也应该是无法区分空格后是参数还是路径。希望尽快修复

**Comment by hui-Zz** [comment]
@MisterZakary  谢谢你找到了一个隐藏Bug😆，一般带参数的程序都会加一个菜单项名称，就没出现过问题……
**原因是这样**：因为用户没有取菜单项名的情况，菜单项名称就会自动命名为everything，那无论是`everything.exe` 还是`everything.exe -s` 菜单里面都会是everything，所以就重叠覆盖掉了后面的参数。
我想了个办法，为了防止自动菜单项名重名就在后面加了空格，这样使用的时候不会重名也看不出来，已经更新了。  

另外空格路径作为参数一般是不同软件有不同要求，用RunAny强行加双引号是不合适的（有些双引号反而会报错），而且也无法根据不同软件智能加不加双引号，如：

`Everything搜索选中内容|Everything.exe -search "%getZz%"`

**Comment by MisterZakary** [comment]
> @MisterZakary 谢谢你找到了一个隐藏Bug😆，一般带参数的程序都会加一个菜单项名称，就没出现过问题……
> **原因是这样**：因为用户没有取菜单项名的情况，菜单项名称就会自动命名为everything，那无论是`everything.exe` 还是`everything.exe -s` 菜单里面都会是everything，所以就重叠覆盖掉了后面的参数。
> 我想了个办法，为了防止自动菜单项名重名就在后面加了空格，这样使用的时候不会重名也看不出来，已经更新了。
> 
> 另外空格路径作为参数一般是不同软件有不同要求，用RunAny强行加双引号是不合适的（有些双引号反而会报错），而且也无法根据不同软件智能加不加双引号，如：
> 
> `Everything搜索选中内容|Everything.exe -search "%getZz%"`

测试用例中也是加了菜单项名称的，实际还是会出现找不到的问题。我个人认为为了减少Bug，配置文件很多地方可以做强制要求，避免产生歧义。其实对用户来说，只要文档清晰，多个引号或者多个什么符号作为标志项也是很简单的事情。

这个是我的配置：
![](https://i.loli.net/2020/05/21/VcB7ufqLPdJDN4j.png)
这个是我的使用截图
![](https://i.loli.net/2020/05/21/qJzf1IuLCZnWBPv.png)
第一项就是正常的，第二项就是找不到。

**Comment by MisterZakary** [comment]
@hui-Zz 
甚至可以强制要求必须写菜单项名称，可以采用 【菜单项名称】|【程序路径/插件代码】|【程序参数/插件参数】的方式。当然我只是提出我个人的建议，如何实现您肯定比我们要清楚。

**Comment by hui-Zz** [comment]
@MisterZakary  如果我发的功能也有问题，那应该跟你的RunAny配置和电脑环境有关了，功能库里的功能我都是测试过可用的

另外我在菜单项编辑窗口中是有一些错误校验的，是帮助刚开始使用RA的用户的。
但是我觉得兼容使用 `RunAny.ini`文件 是不可或缺的，因为当你熟悉RunAny后直接编辑 `RunAny.ini`文件 会带来极大的效率，结合一些功能强大的编辑器软件可以轻松实现批量编辑等等

你加一下QQ群：<a href="https://jq.qq.com/?_wv=1027&k=445Ug7u">246308937【RunAny快速启动一劳永逸】</a>，发给我`RunAnyConfig.ini`这个配置文件，我就可以定位问题，然后问题解决后看写一些详细的错误提示进去。
