### ISSUE TITLE
UI界面错位

### ISSUE THREAD

**Issue by Leoongithub** [hui-Zz/RunAny#59]
![image](https://user-images.githubusercontent.com/10937162/83657460-74985e00-a5f3-11ea-9195-fb9eee440ad9.png)
应该和DPI缩放有关

**Comment by hui-Zz** [comment]
我测试了Win10 下 缩放 100%、125%、150%、175% 五档没有出现你截图中的情况。
麻烦你告知一下你的系统版本、DPI缩放数值、分辨率等数值，谢谢
如果需要尽快解决可以加QQ群：246308937

Leoongithub <notifications@github.com> 于2020年6月3日周三 下午11:40写道：

**Comment by Leoongithub** [comment]
看来是因为我用了非整数的dpi缩放，调成125%之后没有问题了，感谢帮助。
