### ISSUE TITLE
初始启动，需要按两次快捷键才能显示菜单。

### ISSUE THREAD

**Issue by justyyl** [hui-Zz/RunAny#6]
RunAny初次启动，需要按两次快捷键才能显示菜单。
还有返回菜单时，按Esc有时间是一层一层返回，有时是直接隐藏菜单，建议用退格键做菜单层级返回。Esc隐藏菜单。

**Comment by hui-Zz** [comment]
@justyyl  谢谢反馈。初次启动时需要动态加载EXE的图标，有一定延迟，所以在RunAny托盘图标没变前，建议稍等，这时按热键前一次可能是图标未加载完的菜单。
RunAny菜单和系统右键菜单是同一种，所以都是只有一级菜单时Esc键隐藏菜单，展开二级菜单以上Esc键层级返回，而隐藏菜单一般直接按一下Alt键就行了。

**Comment by justyyl** [comment]
谢谢答复，但是Esc时，有时二级菜单以上也是会隐藏，可以说大部分时间都是二级菜单以上按Esc会隐藏，偶尔层级返回，win7 64位系统。
