### ISSUE TITLE
求能够指定每个启动程序的坐标和大小的脚本或功能

### ISSUE THREAD

**Issue by wgy981930674** [hui-Zz/RunAny#60]
求能够指定每个启动程序的坐标和大小的脚本或功能，比如作为启动参数传入。我是程序员，平时需要打开很多程序，我希望程序窗口能够在显示固定的位置上

**Comment by wgy981930674** [comment]
现在会单个更改位置了，多个还需要学习下使用。
发现问题：huiZz_Window[win_move***，窗口移动函数会导致 窗口置顶 ，不知道是什么回事，需要手动取消置顶才能正常

**Comment by hui-Zz** [comment]
窗口改变大小并移动|huiZz_Window[win_move_size_zz](0,0,800,600)

使用方法可以参考文档：
https://hui-zz.gitee.io/runany/#/plugins-help?id=huizz_window窗口操作插件使用方法



wgy981930674 <notifications@github.com> 于2020年10月16日周五 下午5:13写道：
