### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ACG-Q** [hui-Zz/RunAny#61]
## 运行环境
> 版本                            Windows 10 专业版
> 版本号                         2004
> 操作系统内部版本      19041.1052

## 软件版本 v5.7.5
![image](https://user-images.githubusercontent.com/47310744/126435626-dac4f921-0f15-4d7f-a384-a14c2121454f.png)

## 问题
无法使用快捷键 <kbd>`</kbd> 进行呼出

并且也没法, 在后台通过右键呼出菜单

但是, 通过`任务管理器`强制结束程序后, 再重新运行后就运行正常了

**Comment by hui-Zz** [comment]
好的收到，问一下你是用的固态硬盘还是机械硬盘？
另外已经计划后面两三个版本后，会有一些性能优化的更新

**Comment by ACG-Q** [comment]
我是把软件放在机械硬盘的分区磁盘里面
系统是安装在固态硬盘里面
