### ISSUE TITLE
一键直达 功能增强建议

### ISSUE THREAD

**Issue by FerryboatSeranade** [hui-Zz/RunAny#62]
希望能支持 百度网盘分享链接 自动整合密码到原始链接中
应用场景: [油猴插件: 网盘自动提取密码](https://greasyfork.org/zh-CN/scripts/1002-%E7%BD%91%E7%9B%98%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%86%99%E6%8F%90%E5%8F%96%E5%AF%86%E7%A0%81)
![image](https://user-images.githubusercontent.com/41131303/144968903-6d784747-9831-4ba5-a6d1-67eeaddc2c9c.png)

输入:
链接：<a href="https://pan.baidu.com/s/1QHzdRof0edZSR8r1Tm9WEw">https://pan.baidu.com/s/1QHzdRof0edZSR8r1Tm9WEw</a> 
提取码/密码：abcd 
期望输出:   https://pan.baidu.com/s/1QHzdRof0edZSR8r1Tm9WEw#abcd

**Comment by hui-Zz** [comment]
huiZz_Text.ahk v1.2.8 之后都是支持的
