### ISSUE TITLE
弹窗自定义字体大小+能否当数字运算文本中夹杂其它内容时，仍然执行运算？

### ISSUE THREAD

**Issue by tyf2018** [hui-Zz/RunAny#63]
1、请问弹出菜单（见下图）的字体大小支持自定义吗？想把字体变大点，不然4K屏字体太小了。
![image](https://user-images.githubusercontent.com/56342788/146630483-432dd573-1bb8-4f34-af60-69b46027fc33.png)

2、能否当数字运算文本中夹杂其它内容时，仍然执行运算？（跳过不相关内容即可）例如

```
22*33=
测试.不相关内容
2+66*99=

```
仍然执行运算？（目前，这种情况，运算功能不生效）

谢谢！

**Comment by hui-Zz** [comment]
1、 RunAny设置 - 图标设置 - RunAny菜单图标大小改成20以上试一下

2、 下个版本会有自定义一键直达配置，到时候可以自定义正则实现是否任意情况下都执行一键计算
