### ISSUE TITLE
启动路径不支持多个参数

### ISSUE THREAD

**Issue by z775729168** [hui-Zz/RunAny#64]
作者大大你好，谢谢这么棒的软件👏

其实我在使用碰到一些问题。

比如设置这样一个路径：
`%SCOOP%\apps\firefox-portable\current\firefox.exe -profile "%SCOOP%\apps\firefox-portable\current\profile"`，
可以正确打开Firefox，同时打开正确的用户文件。但是如果加上一个Url就不行了。比如：
`%SCOOP%\apps\firefox-portable\current\firefox.exe -profile "%SCOOP%\apps\firefox-portable\current\profile" “https://www.baidu.com"`，
这样既不能打开用户文件，也打不开地址，只是弹出一个空白页。但是如果把它们放在一个快捷方式中是可以正确打开Firefox的。

如果是我使用不当的话，也希望可以不吝赐教😊

**Comment by hui-Zz** [comment]
```diff 
+ %SCOOP%\apps\firefox-portable\current\firefox.exe -profile "%SCOOP%\apps\firefox-portable\current\profile"
- “https://www.baidu.com"
- ↑此处双引号不能为中文双引号，需要英文双引号

RunAny的启动路径等同于在 cmd命令行下执行的，所以如果无法启动，可以复制到cmd里面执行一下，判断命令是否有问题

**Comment by z775729168** [comment]
谢谢回复。
cmd里是对的，但是在runany还是不对，加上路径也不对。比如：
`cmd.exe /c start /D %userprofile% %SCOOP%\apps\firefox-portable\current\firefox.exe -profile "%SCOOP%\apps\firefox-portable\current\profile"  "https://www.baidu.com"`

哦，抱歉，脑袋秀逗了，直接指向一个.lnk就可以了。
