### ISSUE TITLE
最新5.3.5微软杀毒报病毒

### ISSUE THREAD

**Issue by teraStars** [hui-Zz/RunAny#7]
病毒类型：Trojan:Win32/Fuery.B!cl

**Comment by hui-Zz** [comment]
@teraStars

**Comment by hui-Zz** [comment]
@teraStars  5.3版本在众多网友和群友的建议下，新增了大量好用的功能，
可能新功能代码被杀软误认为有问题，但是你可以直接查看代码，即使不懂也可以参照AHK文档知道作用。
RunAny.exe采用原生无加密编译，可以被直接反编译得到源码，与RunAny.ahk完全一致，都是让RunAny变得更加实用方便的好代码！

**Comment by hui-Zz** [comment]
@teraStars  能否麻烦你提供一下系统的版本以及微软杀毒软件的版本，因为目前我几台Win10电脑和群友都没有出现过误报的问题

**Comment by teraStars** [comment]
win10 64位专业版，一直自动更新，已更新到最新，我下载了最新的5.3.6微软仍然报毒。

**Comment by teraStars** [comment]
建议你检查一下自己电脑，我刚才用autohotkey1.1.29版，自己编译生成RunAny.exe程序，微软并未报毒。

**Comment by hui-Zz** [comment]
@teraStars 谢谢你的建议，但是我建议你最好还是不要更新Win10到最新，特别是预览版，我已经不下3次出现严重BUG而重装回退系统版本了。
从你的回复已经可以确认是Windows Defender误报，还是麻烦讲一下它的版本号。
总的来说，谢谢你的反馈，之后我会考虑升级AHK编译器版本。
