### ISSUE TITLE
进入一级菜单以后通过字母顺序去重

### ISSUE THREAD

**Issue by z775729168** [hui-Zz/RunAny#76]
作者大大你好，非常感谢您的软件。

我使用中碰到一些问题，情况是这样

我想把很多网页地址放入runany，为了用字母去重，我就用二级菜单作为字母前缀，如下：
```
        Ariang|http://ariang.zxc.cn
	Adguardhome|http://adh.zxc.cn
	--&D
		D&uplicati|http://backup.zxc.cn
		D&eluge|http://de.zxc.cn
	--&F
		F&reshrss|http://rss.zxc.cn
		F&ileBrowser|http://file.zxc.cn
	--&M
		M&etube|http://yt.zxc.cn
		M&agicmirror|http://mm.zxc.cn
	--&T
		T&ransmission|http://tr.zxc.cn
		T&ower|http://tower.zxc.cn
	--&P
		P&ortainer|http://docker.zxc.cn
		P&hotoview|http://p.zxc.cn
```

如果出现重复的字母就做下一级菜单。不过这样不太优雅。

runany默认的行为是相同的首字母会循环条目，如果可以的话，第二字母以后就开始匹配后面的字母，最好的话同时隐藏其他字母选项，Esc回退上一级菜单，类似搜索一样的功能。

作者大大觉得如何？或者现有功能下有其它的解决方法，望赐教。

**Comment by hui-Zz** [comment]
RunAny推荐启动方式仍是三键启动，也就是：1、启动菜单 2、展开分类 3、运行菜单项
而且以字母分类已经大大超出3键，即使区分第一字母、第二字母，还会有第三字母、第四字母重复…这样下去效率已经不高

所以我推荐你在菜单内依旧用：视频、购物、下载等功能分类来区分网址
然后同时使用RunAny5.8.0推出的新插件：RA搜索框：搜索菜单项，后缀菜单、自定义搜索等
RunAny_SearchBar.ahk （在插件管理 - 下载插件里下载）

插件介绍地址：https://hui-zz.gitee.io/runany/#/plugins/runany-searchbar

这样想按字母启动网址的时候，就使用搜索框插件来启动
忘记网址名字的时候，依然可以在RunAny菜单分类里面去查找，不怕遗忘

**Comment by z775729168** [comment]
谢谢回复。

我认为现有方案大概不行。

runany的优势是按键少，但是也是缺点，如果扩展很多菜单的时候，就要记忆很多按键。
特别重名的时候，需要额外记忆，比如名字是abc，但是a重名了，我必须按b或者其他的而不是a，违反直觉。
搜索是一个办法，但是它失去了runany文件树的优势，全局搜索重名的问题更严重。
在搜索中用快捷键指定一级菜单，也可以，但是我觉得与其分开一个功能，多一个插件，直接利用一级菜单作为搜索入口更简单。

不过这个可能很依赖英文命名。

关于效率的问题，对于菜单少的人，我觉得可以用&之类强制指定的方式，这个功能本身也是一个字母选择的扩展，如果不存在重名应该没有影响的。如果需要更多菜单的人，其实可以额外指定更多的一级菜单用于快速选择，兼顾效率，但是对于子菜单太多的情况，记忆比按键更痛苦。

关于更多二级菜单来分割，一个是我觉得这个做法和我设想的功能是不冲突的，二是我觉得依旧增加了记忆成本，因为有些东西不好通过细分来减少重名。
比如很多自建的项目很微妙，比如Duplicati是一个备份工具，但是我只有一个备份工具，如果建立单独为它一个分类，感觉和用字母类似，比如下载的工具，我只有两个，这样建立分类效率不高。
但是如果从自建的分类再抽象一个大分类，会让我很困惑，比如对于下载归于文件类，媒体类也可以归于文件类，这样分类可能导致一个菜单可能同时符合多个分类，而且这样分类同样违反直觉，对于如何分类的要求也比较高。
比如自建这个分类中，一部分组成一个二级分类，其他因为太少不分类，那么有些东西用字母，有些却需要指定分类，等于是变相的记忆成本，我必须记住哪些东西在分类中再按键，依旧违反直觉。

简单的说，我认为这个功能是对于菜单太多的情况的补充，对于想使用三键的用户应该没有影响，也可以兼容效率。

感谢读到这里，如果有什么想法，希望可以分享一下。

**Comment by hui-Zz** [comment]
正如你提到的，两个重名字母过多的菜单项，应该考虑设置别名来区别
比如：`github` 和 `gitee` 这两个网址前3个字母完全相同
- 此时如果打开频率较低，间隔一星期两星期才打开一次，那想打开时就使用搜索框插件：直接输入github 回车打开，也是非常迅速的
- 如果是每天或两天都会打开，那就推荐用RunAny菜单：
  - 比如`github`比`gitee` 打开频率高，那就设置快捷字母`g`为github
  - `&Github|https://github.com`
  - gitee就用e来表示：`git&ee|https://gitee.com`
  - 还有可以用中文来记忆快捷字母：`码云(&M)|https://gitee.com`

总之，要不就不设置快捷启动，在搜索框打全称启动；要不就是手动设置自己容易记的字母
不应该由RA软件机器帮你定快捷字母，那样不是你自己定的，根本没有记忆点（关键一旦新加名称类似软件，还会自动换字母，导致记忆错乱）
而且菜单项不是一成不变的，你现在下载工具只有两个，以后可能会有N个
备份工具使用频率过低，可以放入`文件&File` 这种大分类中，或者做三级分类

还有你看分类名 `文件&File` ，打开分类的字母不要太好记，成本非常的低
实际上，很长一段时间内我都懒的记，只记了差不多`A W R G V E F S`总共8个字母：`常用(&App)、办公(&Work)、网址(U&RL)、图片(im&G)、影音(&Video)、编辑(&Edit)、文件(&File)、系统(&Sys)`

对，就只记8个字母，展开分类菜单，我再用鼠标去打开应用（可以称之为懒的记的极致）

**不知道你发现没有，这8个字母都在左手边，也就是我左手按两个键打开菜单和分类，右手鼠标马上点，甚至跟他们用搜索框搜索差不多（记的最少速度还快）**

后来嘛，经常鼠标点同一个软件，那自然就会记一下它的首字母，或设置一个字母&，这样就可以盲按三键来启动了（不需要等待菜单显示）

**Comment by z775729168** [comment]
谢谢回复。

第一，我想说的是搜索框插件不适合runany。
如果需要使用搜索框的用户，可能是拥有大量菜单，也存在大量按键设置，那么这些菜单反而会对搜索造成干扰，造成重名更严重。
它在用户只知道一部分非首字母的情况下才有利，或者存在复杂的多级菜单分类。如果不知道菜单的名字，那么利用runany树菜单更有利。

第二，如果是严重重名的情况，不管选择哪种方式都不理想，这里不过是用户的选择差异。
比如`github`和`gitee`的情况，如果记忆`gitee`→`e`，依旧是一种变相的无理记忆。如果多按`ite`，就会维持语义，减少记忆，但是代价是多按三个键。不管哪种方法其实都不好，应该让用户去选择。

第三，分类不该滥用。
确实分类可以减少重名，但是如果特意通过分类减少重名，就会破坏分类的定义。多级分类应该尽量减少使用。
如果我没理解错的话，您希望我通过复制一级分类到下级分类的方式来避免重名？但是，不是一级分类好记的问题，问题是这个分类不适合已经被细分的下级菜单。
如果移动分类，比如一个备份工具，它的界面在网页，本来应该在`网页`，如果为了减少重名把它移动到一级分类的`文件`中，但是我对于`文件`的定义，或者说用法是记录常用的文件或文件夹位置，除非我破坏这个分类定义，这个也是无理记忆。
如果移动到`系统`中，`系统`本来是只关于本地系统的内容，但是备份软件不在本地，也不备份系统，实际是备份各种东西，包括多媒体，文档等。也是破坏了定义。
这种实际也是通过一些变相的无理记忆避免重名。

现在避免重名无非三种。
一种是完全的无理记忆，如果用在runany中使用，就是严格按字母顺序分配菜单快捷键，需要大量记忆，最大利用键位。
一种是折中的无理记忆，利用菜单的首字母，或者自定义中文首字母的方式，应对重名就利用后面的字母，减少记忆，但是对于键位利用已经大大折扣，毕竟受限于名称。
一种是完全的有理记忆，打出菜单名，一种东西不需要记两遍，代价是必须多按键。其实就是搜索框类的软件。

runany必须面对的问题是，它的键位利用率不高，现在提高利用率的方法，无法是利用各种折中的无理记忆，或者完全的无理记忆，但缺少对于有理记忆的支持。
比如现在runany中遇到`github`和`gitee`，可以通过多按一下来定位到另一个，也是一种折中的无理记忆，类似于`g`和`gg`。如果新出现一个g开头的菜单，就变成`ggg`。问题不在于这个快捷键序是否是自动设定的，哪怕设定一个按键，也是增加了额外的记忆。方案的差异不过是形式不同而已。
现在哪怕是完全的无理记忆，最多也就26个字母，但是只要多索引一个字母，就可以扩展到26*26=676个菜单。这样能变相减少多级分类，也更能照顾菜单名和分类的定义。

不是哪种方案好，而是哪种方案都有缺点，如果可以的话，最好让用户自己去选择。

谢谢阅读，如果有疏漏和错误，望指正。

**Comment by z775729168** [comment]
可能比较失礼，不过我想到不错的变通方法了，就是直接启动一个altrun。
稍微有一些问题，比如配置文件在不同地方，不能预览菜单，不能回退，但是可以从任意字母位置开始定位。

谢谢作者大大，讨论启发了我。
