### ISSUE TITLE
自定义图标问题

### ISSUE THREAD

**Issue by Craser001** [hui-Zz/RunAny#78]
请问一下自定义图标支持什么格式，我用png格式发现设置界面显示正常，但快捷菜单要么图标背景变成黑色要么什么都没有，当我想再次更改图标时发现添加图标这个选项不见了。不影响软件使用，只是一个小小的问题，烦请大佬有时间的话看一下
![快捷菜单栏不显示图标](https://user-images.githubusercontent.com/86217242/158139968-c65b53ea-ebaf-4b70-960a-88ec6792fc88.jpg)
![添加图标的地方不见了](https://user-images.githubusercontent.com/86217242/158139976-1014653a-c1d2-49e6-9b88-c4d7a16969f7.jpg)
![设置界面图标正常显示](https://user-images.githubusercontent.com/86217242/158139981-8314e240-423c-489a-ad3c-39c44738cfd8.jpg)
。

**Comment by hui-Zz** [comment]
在RunAny目录下 \RunIcon\ExeIcon\ 里面可以找到 以你菜单项名相同的图标文件
你换另一张图片进去，名字改成一样就可以生效了
