### ISSUE TITLE
有没有64位版本？

### ISSUE THREAD

**Issue by raidsan** [hui-Zz/RunAny#79]
现在是32位软件，启动调用其他程序也是调用它们的32位版本，功能会有限制，例如 Process Hacker 2

**Comment by hui-Zz** [comment]
实际上，现在的RunAny.exe就是AutoHotkey.exe改了一下图标，主要是调用RunAny.ahk脚本来使用的。
目前要用64位，你可以先下载一下Autohotkey（http://ahkscript.org）
然后把里面的64位AutoHotkey.exe 或 AutoHotkeyU64.exe 复制到RunAny目录，然后重命名成RunAny.exe就可以用了

**Comment by hui-Zz** [comment]
上传了 RunAny.exe所有32+64位版本.zip
蓝奏云稳定版下载：https://www.lanzoui.com/b902490/
百度云稳定版下载：https://pan.baidu.com/s/1qxbYAx0UA-u1dkoY-RXZJg
