### ISSUE TITLE
闭源软件？ 

### ISSUE THREAD

**Issue by dotkt** [hui-Zz/RunAny#88]

**Comment by hui-Zz** [comment]
无开源协议的意思是，项目的作者保留一切版权和其权利，
学习自用没什么问题，商用分发需要经过作者同意
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.
