### ISSUE TITLE
Input无法输入到微信聊天框中

### ISSUE THREAD

**Issue by SunSeaShy** [hui-Zz/RunAny#95]
菜单Input项里的内容无法输入到微信里

**Comment by hui-Zz** [comment]
在微信界面上输入短语建议使用 热字符串 或 全局热键的形式
这样可以避免输入焦点带来的问题，也会更方便的输入字符串
https://hui-zz.gitee.io/runany/#/README?id=%e7%83%ad%e5%ad%97%e7%ac%a6%e4%b8%b2

**Comment by SunSeaShy** [comment]
感谢！
