### ISSUE TITLE
runany5.8.2无法在vscode中激活

### ISSUE THREAD

**Issue by zzxcodelife** [hui-Zz/RunAny#99]
遇到的第一个问题，初次运行的时候可以`调用runany命令，但每次重启电脑之后都无法运行，对于这个问题，我新建了一个路径runany文件夹，把整个文件解压放进去，重启几次电脑解决了。
第二个问题，这个方案解决以后，发现无法在vscode中使用runany，我在vscode中尝试了markdown、python都无法调用。请问有没有遇到同样问题的朋友，帮忙解答一下。

**Comment by hui-Zz** [comment]
是这样的，RunAny默认开启了模拟按Ctrl+C来 对选中文件或文字的获取，可以用软件或插件来处理选中的文件或文字的功能

但是在vscode和其他一些编辑器里面，你在编辑区域按Ctrl+C会自动帮你复制一整行的文字，就导致把一整文字当参数传递给你要打开的软件了

你可以每次用RunAny菜单中运行软件后，把鼠标移动到 Ra 的图标上面，就可以看到刚刚是运行的什么路径的软件，看看有没有一些多余的东西加进去导致运行失败了

**Comment by zzxcodelife** [comment]
> 是这样的，RunAny默认开启了模拟按Ctrl+C来 对选中文件或文字的获取，可以用软件或插件来处理选中的文件或文字的功能
> 
> 但是在vscode和其他一些编辑器里面，你在编辑区域按Ctrl+C会自动帮你复制一整行的文字，就导致把一整文字当参数传递给你要打开的软件了
> 
> 你可以每次用RunAny菜单中运行软件后，把鼠标移动到 Ra 的图标上面，就可以看到刚刚是运行的什么路径的软件，看看有没有一些多余的东西加进去导致运行失败了

感谢您的回复，今天我在自己另外一台win10电脑上可以运行，先在这个bug可能和我笔记本电脑为win11系统有关系。

**Comment by zzxcodelife** [comment]
好崩溃，为什么在win11电脑使用这么难受啊，系统小更新重启以后就没法正常使用了，每次都要重新导入文件配置。之前在matlab里面能用，电脑更新以后，matlab里面也无法呼出菜单了。对经常敲点代码的我太不友好了。如果时因为自动Ctrl+C模式的话，有没有什么办法强制RA菜单启动的方法呢？

**Comment by zzxcodelife** [comment]
首先非常感谢开发者hui-Zz的耐心解答，我终于解决了win11中RA无法在vscode、有道云笔记中运行的问题。我有一个单独运行的ahk脚本，这个脚本中有几个复杂的函数，对RA造成了干扰。把这几个函数另存为一个ahk文件，通过Inculde的方式调用，问题就解决了。希望可以帮助后来的朋友。
